services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    hostname: metube
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=MeTube
      - homepage.icon=metube.png
      - homepage.href=http://homelab.local:8081/
      - homepage.description=Baixar vídeos no Youtube
    ports:
      - "8081:8081"
    volumes:
      - ../../../DATA/metube:/downloads