---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

# - My First Group:
#     - My First Service:
#         href: http://localhost/
#         description: Homepage is awesome

# - My Second Group:
#     - My Second Service:
#         href: http://localhost/
#         description: Homepage is the best

# - My Third Group:
#     - My Third Service:
#         href: http://localhost/
#         description: Homepage is 😎

# - System Monitoring:
#     - Glances:
#         icon: glances.png
#         href: http://homelab.local:61208
#         description: System monitoring dashboard
        # widget:
        #   type: glances
        #   url: http://glances:61208
        