---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
title: Minha Homepage
description: A homepage de aplicações em container
background: 
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100
theme: dark

cardBlur: xs # xs, md, etc... see https://tailwindcss.com/docs/backdrop-blur

# favicon: https://www.google.com/favicon.ico

layout:
  Media:
    style: row
    columns: 4
  Developer:
    style: row
    columns: 4

# providers:
#   openweathermap: openweathermapapikey
#   weatherapi: weatherapiapikey

headerStyle: boxed

showStats: true

