services:
  invokeai:
    image: ghcr.io/invoke-ai/invokeai
    runtime: nvidia
    ports:
      - "9090:9090"
    volumes:
      - ../../../DATA/invoke-ai:/invokeai
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]