services:
  invokeai:
    image: ghcr.io/invoke-ai/invokeai
    runtime: nvidia
    ports:
      - "9090:9090"
    volumes:
      - ../../../DATA/invoke-ai:/invokeai
    labels:
      - homepage.group=Development
      - homepage.name=Invoke AI
      - homepage.icon=invoke-ai.png
      - homepage.href=http://homelab.local:9090/
      - homepage.description=Gerador de imagens
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]