services:
  ollama-gpu:
    image: ollama/ollama
    container_name: ollama-gpu
    ports:
      - "11434:11434"
    volumes:
      - ollama-gpu:/root/.ollama
    networks:
      - ollama-ipv6
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # restart: unless-stopped

volumes:
  ollama-gpu:

networks:
  ollama-ipv6:
    enable_ipv6: true
    driver: bridge